"""
Script for creating .txt files for use in alignment on escriptorium. I used this to create training data. We probably won't need this again, unless we need to produce more training data or produce ALTO files for remaining notebooks.

Input: html-input directory containing .html files representing transcripts of individual Tunica notebook pages, i.e. the ones produced for use in EditionCrafter. (These can be generated by editioncrafter/process-xml-output.py.)

Output: txt-output directory containing (1) transcriptions of individual pages with line breaks and (2) merged files of 10 pages at once, without line breaks (this was most useful for alignment)
"""

from bs4 import BeautifulSoup
import os

path_to_input = r"U:\\tunica-files\\escriptorium\\html-input"
path_to_output = r"U:\\tunica-files\\escriptorium\\txt-output"

max_pages = 204

# remove leading "f" and switch page numbers to start at 1, not 0
def process_page_num(num):
    num_int = int(num.replace("f", ""))
    return num_int + 1

# read in files and add to dict
def read_in_files():
    file_names = os.listdir(path_to_input)
    pages = {}
    
    for file in file_names:
        ec_page_num = file.split(".")[0]
        page_num = process_page_num(ec_page_num)
        
        with open(f"{path_to_input}/{file}", 'r', encoding='utf8') as inputfile:
            soup = BeautifulSoup(inputfile, 'html.parser')
            pages[page_num] = soup.get_text().strip()

    return pages

# create a .txt file with line breaks for each individual page
def write_individual_files(pages):
    print("Writing individual files")
    for page_num, contents in pages.items():
        output_file = open(f'{path_to_output}/{page_num}.txt', 'w', encoding="utf-8")
        output_file.write(contents)
        output_file.close()

# create a .txt file with no line breaks for each range of 10 pages
def write_merged_files(pages):
    print("Writing merged files")
    
    start_num = 1
    end_num = -1
    
    while start_num < 204:
        end_num = start_num + 9
        merged_str = ""
        
        for page_num, contents in pages.items():
            if page_num >= start_num and page_num <= end_num:
                contents_joined = ' '.join(contents.splitlines())
                contents_space_stripped = " ".join(contents_joined.split())
                merged_str += contents_space_stripped + " "
        with open(f'{path_to_output}/haas-{start_num}-to-{end_num}.txt', 'w', encoding='utf8') as outputfile:
            outputfile.write(merged_str)
        start_num += 10

def run_program():
    pages = read_in_files()
    write_individual_files(pages)
    write_merged_files(pages)


if __name__ == '__main__':
    run_program()